project:
  type: book

crossref:
  sec-prefix: sección    # (default is "Section")
#  fig-prefix: figure     # (default is "Figure")
#  tbl-prefix: tableau    # (default is "Table")

lang: es

book:
  title: "Notas de Python"
  subtitle: "Ejemplos y aplicaciones."
  author:
    - name: "Luis Miguel De la Cruz Salas"
      affiliation: "Instituto de Geofísica, UNAM"
  favicon: figuras/python1.png
  sidebar: 
##    background: "#F5F5F5"
    logo: figuras/python1.png
    search: true
  cover-image: figuras/python1.png
  sharing: [twitter, facebook, linkedin]
  reader-mode: true
  date: today
  chapters:
    - index.qmd
    - notebooks/01_variables_objetos.ipynb
    - notebooks/02_tipos_basicos.ipynb
    - notebooks/03_operadores.ipynb
    - notebooks/04_expresiones_declaraciones.ipynb
    - notebooks/05_cadenas.ipynb
    - notebooks/06_input.ipynb
    - notebooks/07_archivos.ipynb
    - notebooks/08_control_de_flujo.ipynb
    - notebooks/09_listas.ipynb
    - notebooks/10_tuplas.ipynb
    - notebooks/11_conjuntos.ipynb
    - notebooks/12_diccionarios.ipynb
    - notebooks/13_ds_casting.ipynb
    - notebooks/14_ds_traversing.ipynb
    - notebooks/15_funciones.ipynb
    - notebooks/17_excepciones.ipynb
    - notebooks/23_import.ipynb
#    - glossary.qmd
#    - 5-appendices/A-instalacion.ipynb
#    - references.qmd

#bibliography: references.bib
#csl: apa.csl

format:
  html:
    toc: true
    number-sections: true
    theme: 
      light: [minty, estilos/light.scss]
      dark: [cyborg, estilos/dark.scss]
    code-fold: false
    highlight-style: arrow
    css: estilos/code-blocks.css
  pdf:
    documentclass: scrbook
    number-sections: true
