project:
  type: book
  output-dir: docs
    
crossref:
  custom:
    - key: exm
      kind: float
      reference-prefix: Ejem.
      caption-prefix: Ejem. 
#  sec-prefix: sección    # (default is "Section")
#  fig-prefix: figure     # (default is "Figure")
#  tbl-prefix: tableau    # (default is "Table")

lang: es

extensions:
  iconify:
    set: "octicon"
    size: "1.25em"
    width: "1em"
    height: "1em"
    flip: "horizontal"
    rotate: "0deg"
    inline: true
    mode: "svg"
    style: "color: #b22222;"
      
book:
  title: "Notas de Python"
  subtitle: "Ejemplos y aplicaciones."
  author:
    - name: "Luis Miguel De la Cruz Salas"
      affiliation: "Instituto de Geofísica, UNAM"
  favicon: figuras/python1.png
  sidebar: 
##    background: "#F5F5F5"
    logo: figuras/python1.png
    search: true
  cover-image: figuras/python-logo-master-v3-TM.png
  sharing: [twitter, facebook, linkedin]
  reader-mode: true
  date: today
  chapters:
    - index.qmd
    - part: part1.qmd
      chapters:
        - lecciones/leccion_01.ipynb
        - lecciones/leccion_02.ipynb
  appendices:
    - notebooks/01_variables_objetos.ipynb
    - notebooks/02_tipos_basicos.ipynb
    - notebooks/03_operadores.ipynb
    - notebooks/04_expresiones_declaraciones.ipynb
    - notebooks/05_cadenas.ipynb
    - notebooks/06_input.ipynb
    - notebooks/07_archivos.ipynb
    - notebooks/08_control_de_flujo.ipynb
    - notebooks/09_listas.ipynb
    - notebooks/10_tuplas.ipynb
    - notebooks/11_conjuntos.ipynb
    - notebooks/12_diccionarios.ipynb
    - notebooks/13_ds_casting.ipynb
    - notebooks/14_ds_traversing.ipynb
    - notebooks/15_funciones.ipynb
    - notebooks/16_lambda_expressions.ipynb
    - notebooks/17_excepciones.ipynb
    - notebooks/18_comprehensions.ipynb
    - notebooks/19_iterables_map_filter_reduce.ipynb
    - notebooks/20_decoradores.ipynb
    - notebooks/21_iteradores_generadores.ipynb
    - notebooks/22_funciones_y_docstring.ipynb
    - notebooks/23_import.ipynb
#    - glossary.qmd
#    - 5-appendices/A-instalacion.ipynb
#    - references.qmd

#bibliography: references.bib
#csl: apa.csl

format:
  html:
    toc: true
    number-sections: true
    theme: 
      light: [minty, estilos/light.scss]
      dark: [cyborg, estilos/dark.scss]
    code-fold: false
    highlight-style: arrow
    css: estilos/code-blocks.css
  pdf:
    documentclass: scrbook
    number-sections: true
