# Variables y objetos. {#sec-var_y_obj}

**Objetivo.**
Explicar los conceptos de variables y objetos, cómo es que se declaran y cómo se usan mediante algunos ejemplos.

## Reglas para definir los nombres de las variables. {#sec-reglas_nombres}

En Python las variables:

- son **símbolos** que permiten identificar la información que se almacena en la memoria de la computadora,
- son **nombres** o **etiquetas** para los objetos que se crean en Python,
- se crean con ayuda del operador de asignación `=`,
- no se tiene que establecer explícitamente el tipo de dato de la variable, pues esto se realiza de manera dinámica (**tipado dinámico**).

Los nombres de las variables: 

* pueden contener **letras**, **números** y **guiones bajos** (`_`),
* deben comenzar con una letra o un guion bajo,
* se distingue entre mayúsculas y minúsculas, por ejemplo, `variable` y `Variable` serán nombres diferentes.
* puede contener caracteres Unicode (véase [@sec-unicode] ).

## Variables básicas. {#sec-var_basicas}

Los siguientes ejemplos son definiciones de variables con nombres válidos:

* El nombre de la variable con minúsculas, el valor es de tipo cadena (usamos comillas dobles para definir una cadena):

In [2]:
gabo = "Gabriel García Márquez"   

* El nombre de la variable contiene un número, el valor es de tipo entero:

In [3]:
gabo25 = 25  

* El nombre de la variable comienza con `_`, el valor es de tipo flotante:

In [4]:
_gabo = 3.1416  

* El nombre nombre de la variable contiene mayúsculas y minúsculas, el valor es de tipo número complejo: parte real `+` parte imaginaria (con `j`):

In [7]:
GaboComplejo = 3 + 2j  

El nombre de la variable contiene un `_`, el valor es de tipo lógico

In [8]:
gabo_logico = True 

Para imprimir el contenido de las variables antes definidas usamos la función `print()` como sigue:

In [2]:
print(gabo)
print(gabo25)
print(_gabo)
print(GaboComplejo)
print(gabo_logico)

Gabriel García Márquez
25
3.1416
(3+2j)
True


El tipo de cada variable se obtiene usando la función `type()`:

In [3]:
type(gabo)

str

Observa que la variable gabo es de tipo `str`.

Python proporciona los siguientes tipos de variables básicas:

* numéricos: `int`, `float`, `complex`,
* cadenas: `str` y
* lógicos: `True` y `False`.

En el [Capítulo @sec-tipos_basicos] se describen estos tipos básicos en detalle.

## Funciones incorporadas (*Built-in functions*). {#sec-fun_incorporadas}

Las funciones `print()` y `type()`, empleadas en los ejemplos anteriores, son conocidas como **Funciones incorporadas** (*Built-in functions*) en Python, las cuales siempre están disponibles para usarse en cualquier código. La lista completa de estas funciones se puede consultar en <a href="https://docs.python.org/3/library/functions.html" target="_blank" rel="noopener">https://docs.python.org/3/library/functions.html</a>.

A lo largo de este texto se introducirán algunas de estas funciones con ejemplos sencillos. En este capítulo particularmente veremos el uso de las funciones: `print()`, `type()`, `id()`, `chr()`, `ord()`, `del()`.

La función `print()` imprime el contenido de una variable y puede recibir varios argumentos a la vez, por ejemplo:

In [36]:
print(gabo, gabo25)

Gabriel García Márquez 25


Se puede imprimir el resultado de una operación:

In [37]:
print(3 * 4)

12


También imprime el resultado de otras funciones por ejemplo:

In [38]:
print(type(gabo))

<class 'str'>


En este caso se imprime el tipo de la variable `gabo`. Observa que se obtiene más información, particulamente nos dice que `gabo` es un **objeto** de la clase  `'str'`. Hablaremos un poco más de objetos y clases en la [@sec-objetos_nombres].

## Variables con mayúsculas y minúsculas. {#sec-var_mayusculas_minusculas}

Python es sensitivo a mayúsculas y minúsculas en los nombres de las variables. En el ejemplo que sigue se definen tres variables distintas:

In [7]:
pi = 3.14     
PI = 31416e-4 
Pi = 3.141592

* La variable `pi` hace referencia al número flotante $3.14$.
* La variable `PI` hace referencia al número flotante $31416 \times 10^{-4}$ (se usa notación científica `31416e-4`) que es equivalente a $3.1416$.
* La variable `Pi` hace referencia al número flotante $3.141592$.

Estas tres variables son diferentes y se almacenan en lugares diferentes en la memoria de la computadora. La siguiente tabla muestra de manera esquemática los conceptos de nombre, valor e identificador en memoria de una variable:

|Nombre| | Valor | id en memoria |
|--:|--|:--|:-:|
|`pi` |$\rightarrow$| 3.14 | 140425110809872|
|`PI` |$\rightarrow$| 3.1416 | 140425110112240|
|`Pi` |$\rightarrow$| 3.141592 | 140425110112016|

El identificador en memoria de cada variable es un número entero, el cual puede cambiar en cada ejecución. La función `id()` permite conocer el identificador en la memoria de cada variable:

In [8]:
id(pi)

2124418474032

In [9]:
id(PI)

2124422132240

In [10]:
id(Pi)

2124422132368

Observa que cada variable tiene un número de identificador diferente. 

Es posible imprimir el valor de la variable, su tipo y su identificador en una sola línea de código como sigue:

In [11]:
print(pi, type(pi), id(pi))
print(PI, type(PI), id(PI))
print(Pi, type(Pi), id(Pi))

3.14 <class 'float'> 2124418474032
3.1416 <class 'float'> 2124422132240
3.141592 <class 'float'> 2124422132368


## Objetos y sus nombres. {#sec-objetos_nombres}

Python es un lenguaje **Orientado a Objetos**. 

* Todo lo que definimos será un objeto de una clase determinada.
* Una clase define atributos y métodos para los objetos.
* Python tiene definidas clases de las cuales es posible construir objetos.

En los ejemplos anteriores, en donde se han definido algunas variables, lo que realmente está pasando es que se están creando objetos de diferente tipo (o clase) y se les da un nombre. Por ejemplo, la siguiente declaración:

```python
a = 1
```
crea el objeto `1` de tipo entero (`<class 'int'>`) cuyo nombre es `a`.

Si hacemos lo siguiente:

```python
b = a
```

se crea otro nombre para el mismo objeto `1`,  **NO se crea otro objeto**. 

Veamos lo anterior en la siguiente celda de código:

In [39]:
a = 1
b = a
print(a, type(a), id(a))
print(b, type(b), id(b))

1 <class 'int'> 140730842948520
1 <class 'int'> 140730842948520


Observa que las variables `a` y `b` tienen el mismo identificador, lo que significa que son dos nombres para el mismo valor `1`.

Ahora observa el siguiente código y su resultado:

In [41]:
a = 1
b = a
print(a, id(a), type(a))
print(b, id(b), type(b))

b = 5.0
print(a, id(a), type(a))
print(b, id(b), type(b))

1 140730842948520 <class 'int'>
1 140730842948520 <class 'int'>
1 140730842948520 <class 'int'>
5.0 2124422131056 <class 'float'>


* Nota que inicialmente `a` y `b` tienen el mismo identificador en memoria, por lo que son dos nombres para el mismo objeto `1` que es de tipo entero.
* Posteriormente, se crea el nuevo objeto `5.0`, un flotante, y se le da el nombre `b`; en ese momento `a` y `b` hacen referencia a dos objetos diferentes y sucede que:
    * el contenido de `b` es `5.0`,
    * `b` tiene un identificador diferente al de `a`
    * y `b` ahora es de tipo flotante.

Esta conceptualización de objetos y sus nombres es muy importante cuando se manejan estructuras de datos más complejas.

::: {.callout-note}
## Nota.

Usaremos el término **variable** para referirnos a los nombres de los **objetos**. Cuando sea conveniente usaremos el término **objeto**. 
:::

## Definición de varios nombres a la vez. {#sec-varios_nombres}

La siguiente declaración genera tres nombres para el mismo valor `25`.

In [42]:
x = y = z = 25

print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))

Observa que se creó el objeto `25` de tipo `<class 'int'>` y los nombres `x`, `y` y `z` son nombres diferentes para el mismo objeto, lo cual se verifica observando que el identificador de cada variable es el mismo.

Hagamos ahora lo siguiente:

In [44]:
y = 2.7182

print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))

25 <class 'int'> 140730842949288
2.7182 <class 'float'> 2124422132432
25 <class 'int'> 140730842949288


Observa que la variable `y` es de tipo flotante cuyo valor es `2.7182`.


Podemos eliminar el nombre `x` con la función `del()`:

In [45]:
del(x)

Ahora ya no es posible hacer referencia al objeto `25` usando el nombre `x`. Si intentamos imprimir `x` se generará un error indicando lo anterior:

In [46]:
print(x)

NameError: name 'x' is not defined

::: {.callout-note}
## Nota.

Observa que Python nos proporciona mucha información acerca del error. En este caso el error es de tipo `NameError`. Más información al respecto la puedes encontrar en el [Capítulo @sec-errores_excepciones].
:::

Sin embargo, aún es posible hacer referencia al objeto `25` usando el nombre `z`:

In [47]:
print(z, type(z), id(z))

25 <class 'int'> 140730842949288


El objeto `25` será eliminado de la memoria cuando ya no exista un nombre que haga referencia a él. Entonces, si eliminamos `z` se elimina también el objeto `25` pues ya no habrá ningún nombre que haga referencia a él: 

In [48]:
del(z)

Ahora si intentamos imprimir el contenido de la variable `z` obtendremos un error:

In [49]:
print(z, type(z), id(z))

NameError: name 'z' is not defined

## Asignación múltiple. {#sec-asignacion_mult}

Podemos hacer una asignación múltiple de objetos diferentes a variables diferentes, por ejemplo:

In [1]:
x, y, z = "una cadena", 3.141592, 50

print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))

una cadena <class 'str'> 2085440089584
3.141592 <class 'float'> 2085414243824
50 <class 'int'> 140714900203976


Como se observa, las variables `x`, `y` y `z` hacen referencia a diferentes objetos de distinto tipo.

## Caracteres Unicode {#sec-unicode}


**Unicode** es un estándar para la codificación de caracteres, que permite el tratamiento informático, la transmisión y visualización de textos de muchos idiomas y disciplinas técnicas. Unicode intenta tener universalidad, uniformidad y unicidad.  

Unicode define tres formas de codificación bajo el nombre UTF (Unicode Transformation Format): UTF8, UTF16, UTF32. Véase <a href="https://es.wikipedia.org/wiki/Unicode" target="_blank" rel="noopener">https://es.wikipedia.org/wiki/Unicode</a> para más información.

En Python se utiliza la codificación unicode, podemos saber el tipo de codificación como sigue:

In [52]:
# Importamos el módulo sys
import sys

# Imprimimos el tipo de codificación
sys.stdout.encoding 

'UTF-8'

::: {.callout-note}
## Nota.

En la celda anterior estamos usando `import`. Esta declaración importa las bibliotecas que se requieran para realizar alguna tarea. En este caso se importa `sys` que contiene módulos, funciones y variables para acceder a información del sistema. Una explicación detallada de cómo funciona `import` la puedes encontrar en la [Sección @sec-import].
:::

La compatibilidad con UTF-8 en Python significa que se puede leer, escribir y manipular archivos de datos provenientes de fuentes diversas como archivos binarios, bases de datos, APIs web, entre muchas otras; estas fuentes pueden contener texto en diferentes idiomas y codificaciones.

A continuación se muestran algunos ejemplos de nombres de variables que contienen caracteres unicode:

In [53]:
# Acentos y caracteres de idiomas en el nombre de variables
México = "en el ombligo de la luna"
español = "lengua romance"
français = "langues romanes"
Ελληνικά = "Griego"
Русский = "Ruso"

# Símbolos matemáticos
𝜋 = 3.1416
ℏ = 6.626e-34

Estas variables se pueden usar como cualquier otra, por ejemplo podemos imprimir su contenido, determinar su tipo y su identificador en memoria, y las podemos usar en operaciones:

In [54]:
print(México, type(México), id(México))
print(𝜋, type(𝜋), id(𝜋))
print(2 * 𝜋)

en el ombligo de la luna <class 'str'> 2124429492432
3.1416 <class 'float'> 2124422130800
6.2832


También es posible imprimir el caracter unicode y su valor como sigue:

In [55]:
# Imprimimos el valor de la variable Ελληνικά
print("Ελληνικά = ", Ελληνικά)

Ελληνικά =  Griego


Los códigos Unicode de cada caracter se pueden dar en decimal o hexadecimal, por ejemplo para el símbolo $\pi$ se tiene el código decimal `120587` y hexadecimal `0x1D70B`. La función `chr()` convierte el código unicode en el caracter correspondiente:

In [56]:
# Código hexadecimal del caracter 𝜋
chr(0x1D70B)

'𝜋'

In [57]:
# Código decimal del caracter 𝜋
chr(120587)

'𝜋'

La función `ord()` obtiene el código Unicode de un caracter y lo regresa en decimal:

In [3]:
ord("𝜋")

120587

También es posible obtener más información de los códigos unicode como sigue:

In [7]:
# Importamos el módulo unicodedata
import unicodedata 

print("       Símbolo:", "𝜋")
print("Código decimal:", ord("𝜋"))
print("     Categoría:", unicodedata.category("𝜋"))
print("Nombre oficial:", unicodedata.name("𝜋"))

       Símbolo: 𝜋
Código decimal: 120587
     Categoría: Ll
Nombre oficial: MATHEMATICAL ITALIC SMALL PI


Para más información véase: <a href="https://docs.python.org/3/howto/unicode.html" target="_blank" rel="noopener">https://docs.python.org/3/howto/unicode.html</a>

También en los siguientes dos enlaces se pueden obtener los códigos UTF8 de diferentes caracteres especiales:

* <a href="https://www.compart.com/en/unicode/html" target="_blank" rel="noopener">HTML Entities</a>
* <a href="https://www.unicode.org/charts/" target="_blank" rel="noopener">Unicode 17.0 Character Code Charts</a>

## Nombres inválidos para variables. {#sec-nombres_invalidos}

Los siguientes ejemplos **NO SON VÁLIDOS** para el nombre de variables. Al ejecutar las celdas se obtendrá un error en cada una de ellas.

In [60]:
1luis = 20      # No se puede iniciar con un número

SyntaxError: invalid decimal literal (953519616.py, line 1)

In [61]:
luis$ = 8.2323  # No puede contener caracteres especiales

SyntaxError: invalid syntax (3857869541.py, line 1)

In [62]:
for = 35        # Algunos nombres ya están reservados

SyntaxError: invalid syntax (2521306807.py, line 1)

### Palabras reservadas. {#sec-palabras_reservadas}

Como vimos en la celda anterior, no es posible usar las palabras reservadas de Python para nombrar variables. La lista de palabras reservadas se puede consultar con la siguiente expresión:

In [63]:
help("keywords")


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

